### ISSUE TITLE
Warnings on connection

### ISSUE THREAD

**Issue by mrocklin** [dask/gcsfs#104]
I've just `pip install gcsfs` from what I believe to be a somewhat fresh environment.  On trying to connect I get a number of warnings that I'm not able to easily understand.  Things do seem to work afterwards though.

```python
In [1]: import gcsfs

In [2]: fs = gcsfs.GCSFileSystem()
_call exception: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d54183d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2d54183d30>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d54183d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/google/auth/transport/requests.py", line 120, in __call__
    **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d54183d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))

The above exception was the direct cause of the following exception:
```

**Comment by martindurant** [comment]
Unless told otherwise, gcsfs tries to connect using the following sequence of methods, in order: 'google_default', 'cache', 'cloud', 'anon'. The traceback looks to me as if 'cloud' is being attempted from somewhere not in google, or the user has no access to the google metadata service. What kind of connection do you end up with, `gcsfs.method`?

**Comment by martindurant** [comment]
So, indeed, all auth mechanisms failed. The metadata service failure is expected if you are not on google (although the warnings are annoying), and we did see something like this before when on google, but with firewall rules that do not allow the connection. Generally speaking, it's better to know which auth method you want and specify explicitly (`token=`).
