### ISSUE TITLE
Can't open gcsfuse-mounted HDF5 file with h5py

### ISSUE THREAD

**Issue by ryan-williams** [dask/gcsfs#107]
First I ran:
```
gcsfuse <bucket> /tmp/<bucket>
```

Then, attempting to open an HDF5 file with [h5py](http://www.h5py.org/):

```
>>> from h5py import *
>>> input = '/tmp/<bucket>/file'
>>> f = File(input, 'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "…/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

I'm not sure whether this is likely a bug in h5py or gcsfuse; I can see the file with e.g. `ls` or `or.path.getsize`, so gcsfuse seems to be doing its job, but my guess is that there is some syscall or access pattern in h5py that in not playing nicely with gcsfuse.

([mostly-irrelevant discussion of this error message in h5py](https://github.com/h5py/h5py/issues/757))

**Comment by martindurant** [comment]
I haven't tried specifically with h5py , but we have seen success using xarray to open netcdf/hdf files via gcsfuse. You could turn on logging to see what's going on.

**Comment by martindurant** [comment]
The caching is a subtle thing, I hope clear in the code of gcsfuse - there is a special case for the start of the file, since that metadata tends to get accessed a lot for all operations. So we keep the start of the file in memory regardless, but use read-ahead elsewhere. This is far from the biggest file that gcsfuse would have been used for - have you tried opening with xarray? Those were generally netCDF files, but the usage of the driver may be different enough for things to work for you.

**Comment by shenghuanjie** [comment]
Having the same issue here. I'm using some existing pipelines with h5py.
Is there a solution to this?

**Comment by shenghuanjie** [comment]
Having the same issue here. Is there a solution for this? I'm using some existing pipelines with h5py.
```
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.read()

h5py/_proxy.pyx in h5py._proxy.dset_rw()

h5py/_proxy.pyx in h5py._proxy.H5PY_H5Dread()

OSError: Can't read data (file read failed: time = Thu Feb 20 18:25:04 2020
, filename = '/Users/shengh4/data/genia-runs/saturn/190725_PEG-POL-HTP_01_saturn_WSY13R05C08_cycle02/P_000_190726022357_ggc27-keeper_ac-analysis_v15.0.0/annotations.h5', file descriptor = 58, errno = 57, error message = 'Socket is not connected', buf = 0x7fd84eff0e00, total read size = 1411, bytes this sub-read = 1411, bytes actually read = 18446744073709551615, offset = 623200228)
```

**Comment by martindurant** [comment]
With a newer version of h5py, you shouldn't need to use FUSE at all, just open the file directly

```
of = gcs.open('filename', 'rb')
h = h5py.File(of)
```

**Comment by shenghuanjie** [comment]
> With a newer version of h5py, you shouldn't need to use FUSE at all, just open the file directly
> 
> ```
> of = gcs.open('filename', 'rb')
> h = h5py.File(of)
> ```

Thanks. I was using a existing conda environment. The problem has been resolved after update.
