### ISSUE TITLE
ConnectionError - retriable but crashes on flush

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#128]
Sorry for below ill-formatted "stacktrace", this is from Google Stackdriver Logging and produced by Cloud Functions (GCF). 

As you can read though, 

- our code (`split_file.py`) writes some data to a `gcsfs` file-obj
- `gcsfs` determines it's time to flush the cache and upload the chunk to GCS
- that fails, `requests` raises a `ConnectionError` 
- although retriable and [this recent commit](https://github.com/dask/gcsfs/commit/323ac558d4c18297db51d0855bd31a6debada607), gcsfs did **not** catch this hence GCF terminates the execution and tries again (until successful...)

That error should have been treated as a warning, allowing for `gcsfs`/`requests` to try the chunk upload again.

```
A  split_file 393356123294863     return self._sslobj.read(len, buffer) split_file 393356123294863 
A  split_file 393356123294863 urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) split_file 393356123294863 
A  split_file 393356123294863 During handling of the above exception, another exception occurred: split_file 393356123294863 
E  split_file 393356123294863 Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 349, in run_background_function
    _function_handler.invoke_user_function(event_object)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 215, in invoke_user_function
    return call_user_function(request_or_event)
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 212, in call_user_function
    event_context.Context(**request_or_event.context))
  File "/user_code/main.py", line 236, in split_file
    v.extract_segments()
  File "/user_code/main.py", line 144, in extract_segments
    o_file.write(output_line.encode('utf-8'))
  File "/env/local/lib/python3.7/site-packages/gcsfs/core.py", line 1328, in write
    self.flush()
  File "</env/local/lib/python3.7/site-packages/decorator.py:decorator-gen-33>", line 2, in flush
  File "/env/local/lib/python3.7/site-packages/gcsfs/core.py", line 51, in _tracemethod split_file 393356123294863 
  undefined
A  split_file 393356123294863     return f(self, *args, **kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/gcsfs/core.py", line 1374, in flush split_file 393356123294863 
A  split_file 393356123294863     self._initiate_upload() split_file 393356123294863 
A  split_file 393356123294863   File "</env/local/lib/python3.7/site-packages/decorator.py:decorator-gen-35>", line 2, in _initiate_upload split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/gcsfs/core.py", line 51, in _tracemethod split_file 393356123294863 
A  split_file 393356123294863     return f(self, *args, **kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/gcsfs/core.py", line 1440, in _initiate_upload split_file 393356123294863 
A  split_file 393356123294863     json={'name': self.key, 'metadata': self.metadata}) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post split_file 393356123294863 
A  split_file 393356123294863     return self.request('POST', url, data=data, json=json, **kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 201, in request split_file 393356123294863 
A  split_file 393356123294863     method, url, data=data, headers=request_headers, **kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request split_file 393356123294863 
A  split_file 393356123294863     resp = self.send(prep, **send_kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send split_file 393356123294863 
A  split_file 393356123294863     r = adapter.send(request, **kwargs) split_file 393356123294863 
A  split_file 393356123294863   File "/env/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send split_file 393356123294863 
A  split_file 393356123294863     raise ConnectionError(err, request=request) split_file 393356123294863 
A  split_file 393356123294863 requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) split_file 393356123294863 
D  split_file 393356123294863 Function execution took 48623 ms, finished with status: 'crash' split_file 393356123294863 

```

**Comment by martindurant** [comment]
Are you saying that ConnectionResetError should be in the list of retriable exceptions, but currently isn't, or that it is but isn't being caught?

**Comment by yiga2** [comment]
I only saw in the commit that `requests.exceptions.ConnectionError` was marked as retriable. I assume there is a lgoc that handles retries in that case but maybe not in all scenarios (methods ?)

**Comment by martindurant** [comment]
It only appears here: https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L478 , and indeed you are probably right that this same logic should appear in the _initate_upload , _simple_upload and _upload_chunk as well as _fetch_range - ideally factored out as a single function called from each of those places.

**Comment by yiga2** [comment]
Glad you identified the  "issue" ! I understand this possibly requires substantial changes and testing but a PR for this is honestly beyond my knowledge, so I will wait until you have a chance  😉

Conceptually, should the `requests` dependency not handle (and report) retries accordingly ? Many projects/libs rely on that so it would make sense to me - another debate i am sure...

**Comment by yiga2** [comment]
I have actually submitted a PR for this for review.

**Comment by yiga2** [comment]
Resolved by https://github.com/dask/gcsfs/pull/133
