### ISSUE TITLE
GCSFileSystem.cat fails for requester pays objects

### ISSUE THREAD

**Issue by TomAugspurger** [dask/gcsfs#216]
```pytb
fs = gcsfs.GCSFileSystem(token="google_default", project="dask-demo-182016")

In [13]: fs.open('gcsfs-testing-requesterpays/rasm.zarr/.zgroup').read()
Out[13]: b'{\n    "zarr_format": 2\n}'

In [14]: fs.cat('gcsfs-testing-requesterpays/rasm.zarr/.zgroup')
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-14-7d43a4aa534b> in <module>
----> 1 fs.cat('gcsfs-testing-requesterpays/rasm.zarr/.zgroup')

</Users/taugspurger/miniconda3/envs/filesystems/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

~/sandbox/gcsfs/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     48         logger.log(logging.DEBUG - 1, tb_io.getvalue())
     49
---> 50     return f(self, *args, **kwargs)
     51
     52

~/sandbox/gcsfs/gcsfs/core.py in cat(self, path)
    855         u2 = self.url(path)
    856         r = self.session.get(u2)
--> 857         r.raise_for_status()
    858         if "X-Goog-Hash" in r.headers:
    859             # if header includes md5 hash, check that data matches

~/miniconda3/envs/filesystems/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    938
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941
    942     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/download/storage/v1/b/gcsfs-testing-requesterpays/o/rasm.zarr%2F.zgroup?alt=media
```

Seems like `.cat` goes directly though `.session` rather than `._call`.

This blocks using requester pays buckets via intake-xarray, since it uses `.cat` on a file.

```pytb
HTTPError                                 Traceback (most recent call last)
~/sandbox/filesystem_spec/fsspec/mapping.py in __getitem__(self, key, default)
     75         try:
---> 76             result = self.fs.cat(key)
     77         except:  # noqa: E722

</Users/taugspurger/miniconda3/envs/filesystems/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

~/sandbox/gcsfs/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     49
---> 50     return f(self, *args, **kwargs)
     51

~/sandbox/gcsfs/gcsfs/core.py in cat(self, path)
    856         r = self.session.get(u2)
--> 857         r.raise_for_status()
    858         if "X-Goog-Hash" in r.headers:

~/miniconda3/envs/filesystems/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941
```

**Comment by TomAugspurger** [comment]
Just FYI, @rabernat, @jhamman, fixing this is necessary for `intake-xarray` to work on a requester-pays bucket.

But with my changes in #217, the following works

```yaml
plugins:
  source:
    - module: intake_xarray

sources:

  rasm:
    description: description
    driver: zarr
    args:
      urlpath: 'gcs://gcsfs-testing-requesterpays/rasm.zarr/'
``` 

```python
In [1]: import intake
   ...:
   ...: cat = intake.Catalog("catml.yaml")
   ...: cat.rasm.to_dask()

/Users/taugspurger/miniconda3/envs/filesystems/lib/python3.7/site-packages/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Out[1]:
<xarray.Dataset>
Dimensions:  (time: 36, x: 275, y: 205)
Coordinates:
  * time     (time) object 1980-09-16 12:00:00 ... 1983-08-17 00:00:00
    xc       (y, x) float64 dask.array<chunksize=(103, 275), meta=np.ndarray>
    yc       (y, x) float64 dask.array<chunksize=(103, 275), meta=np.ndarray>
Dimensions without coordinates: x, y
Data variables:
    Tair     (time, y, x) float64 dask.array<chunksize=(9, 52, 138), meta=np.ndarray>
Attributes:
    NCO:                       "4.6.0"
    comment:                   Output from the Variable Infiltration Capacity...
    convention:                CF-1.4
    history:                   Tue Dec 27 14:15:22 2016: ncatted -a dimension...
    institution:               U.W.
    nco_openmp_thread_number:  1
    output_frequency:          daily
    output_mode:               averaged
    references:                Based on the initial model of Liang et al., 19...
    source:                    RACM R1002RBRxaaa01a
    title:                     /workspace/jhamman/processed/R1002RBRxaaa01a/l...
```

```python

```

But if you aren't authenticated,


```pytb
_call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/gcsfs/gcsfs/core.py", line 518, in _call
    validate_response(r, path)
  File "/Users/taugspurger/sandbox/gcsfs/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
_call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/Users/taugspurger/sandbox/gcsfs/gcsfs/core.py", line 518, in _call
    validate_response(r, path)
  File "/Users/taugspurger/sandbox/gcsfs/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
```
