### ISSUE TITLE
Batch moving data always logs a few warnings which don't make sense

### ISSUE THREAD

**Issue by pvanderlinden** [dask/gcsfs#247]
When I do a batch request (copying/removing a whole directory), I get several of these messages:

```
urllib3.connectionpool - WARNING - Failed to parse headers (url=https://www.googleapis.com:443/batch): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/opt/conda/default/lib/python3.6/site-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/opt/conda/default/lib/python3.6/site-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
```

It seems like something is wrong, but the operation is succesfull. Is there an idea what this means?

**Comment by martindurant** [comment]
Anecdotally, I have heard that this may be an issue with openSSL. Can you try with different versions to see if it goes away?

**Comment by pvanderlinden** [comment]
This is with the latest version of openSSL though:
```
> openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

They just released a new version about a week ago, I might be able to check next week.
