### ISSUE TITLE
Files with %20 in filename cant be read

### ISSUE THREAD

**Issue by leberknecht** [dask/gcsfs#304]
**What happened**:
I have a file on my bucket that does have `%20` in the filename (not the whitespace " ")

**What you expected to happen**:
Being able to read the file 

**Minimal Complete Verifiable Example**:
First create the file on the bucket:
```bash
echo "test" > /tmp/test%20file.txt 
gsutil cp /tmp/test%20file.txt gs://my-bucket/
```
Then i will try to load it
```python
>>> import pandas as pd
>>> pd.read_csv('gs://my-bucket//tmp/test%20file.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/pandas/io/common.py", line 192, in get_filepath_or_buffer
    filepath_or_buffer, encoding=encoding, compression=compression, mode=mode
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/pandas/io/gcs.py", line 17, in get_filepath_or_buffer
    filepath_or_buffer = fs.open(filepath_or_buffer, mode)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 959, in _open
    **kwargs
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 1038, in __init__
    **kwargs
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/fsspec/spec.py", line 1134, in __init__
    self.details = fs.info(path)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 743, in info
    out = self.ls(path, detail=True, **kwargs)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 767, in ls
    out = self._list_objects(path)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 585, in _list_objects
    return [self._get_object(path)]
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 549, in _get_object
    bucket, self._call("GET", "b/{}/o/{}", bucket, key).json()
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 487, in _call
    validate_response(r, path)
  File "/home/leberle/dev/efi/risk-model/venv/lib/python3.7/site-packages/gcsfs/core.py", line 122, in validate_response
    raise FileNotFoundError
FileNotFoundError
```

**Anything else we need to know?**:
This happens due to https://github.com/dask/gcsfs/blob/77b599382cdac6108d24f3585bb0005d2de3d61e/gcsfs/core.py#L103
I would suggest to make this replacing optional. 

**Environment**:

- Dask version: fs-gcsfs 1.0.0, gcsfs 0.6.2
- Python version: 3.7
- Operating System: linux arch
- Install method (conda, pip, source): pip

**Comment by leberknecht** [comment]
ah wait...hm that doesnt make sense...sorry, i misread the s.replace.

**Comment by leberknecht** [comment]
Ah! Escaping the `%` with `%25` did the trick. Nevermind!

**Comment by MarineChap** [comment]
Hello, happy to see that you find your way out. I am closing the issue then. 
Have a good day.
