### ISSUE TITLE
Unexpected ParseError

### ISSUE THREAD

**Issue by eric-czech** [dask/gcsfs#318]
I saw this when running a long job that writes Zarr archives on GS:

```
Traceback (most recent call last):
  File "scripts/gwas.py", line 420, in <module>
    fire.Fire()
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/gwas.py", line 260, in run_qc_1
    save_dataset(ds, output_path)
  File "scripts/gwas.py", line 70, in save_dataset
    ds.to_zarr(store, mode="w", consolidated=True)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/xarray/core/dataset.py", line 1652, in to_zarr
    return to_zarr(
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/xarray/backends/api.py", line 1369, in to_zarr
    writes = writer.sync(compute=compute)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/xarray/backends/common.py", line 155, in sync
    delayed_store = da.store(
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/dask/array/core.py", line 981, in store
    result.compute(**kwargs)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/client.py", line 1986, in gather
    return self.sync(
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/eczech/repos/ukb-gwas-pipeline-nealelab/.snakemake/conda/b5bd29d8/lib/python3.8/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/dask/array/core.py", line 3724, in store_chunk
  File "/opt/conda/lib/python3.8/site-packages/dask/array/core.py", line 3713, in load_store_chunk
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1115, in __setitem__
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1210, in set_basic_selection
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1501, in _set_basic_selection_nd
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1550, in _set_selection
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1664, in _chunk_setitem
  File "/opt/conda/lib/python3.8/site-packages/zarr/core.py", line 1729, in _chunk_setitem_nosync
  File "/opt/conda/lib/python3.8/site-packages/fsspec/mapping.py", line 152, in __setitem__
  File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1504, in __exit__
  File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1472, in close
  File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1343, in flush
  File "/opt/conda/lib/python3.8/site-packages/gcsfs/core.py", line 1402, in _initiate_upload
  File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 68, in sync
  File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 52, in f
  File "/opt/conda/lib/python3.8/site-packages/gcsfs/core.py", line 1486, in initiate_upload
  File "/opt/conda/lib/python3.8/site-packages/gcsfs/core.py", line 525, in _call
  File "/opt/conda/lib/python3.8/site-packages/gcsfs/core.py", line 507, in _call
  File "/opt/conda/lib/python3.8/site-packages/gcsfs/core.py", line 1228, in validate_response
Exception: Parse Error
```

I have no idea how to reproduce this, but I think if nothing else this error could be much more informative.

This occurred with `gcsfs==0.7.1`.

**Comment by martindurant** [comment]
Hm, that doesn't really give me a lot to go on either. You can get more information out of gcsfs by setting the environment variable GCSFS_DEBUG (or configuring the "gcsfs" logger).

Anecdotally, there does seem to be an increasing range of strange HTTP errors that are, in essence, retriable. This may be another case. I would appreciate improvements to  `validate_response` to provide more information in exceptions.
