### ISSUE TITLE
Insufficient Permission when writing in Google Storage

### ISSUE THREAD

**Issue by albert17** [dask/gcsfs#337]
I am not able to write data in Google Storage when using `gcsfs`, I get insufficient permission error. However, I am able to write data using `gsutil cp`.

I am running (btw, DEBUG is not showing anything)
```
import gcsfs
import os

DEBUG = os.environ.get('GCSFS_DEBUG', True)

fs = gcsfs.GCSFileSystem()
f = fs.open("merlin-datasets/test.txt", 'wb')
f.write(2*2**20 * b'a')
f.close()
```
And I am getting this error 
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    f.close()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1483, in close
    self.flush(force=True)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1354, in flush
    self._initiate_upload()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1409, in _initiate_upload
    self.metadata,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1492, in initiate_upload
    headers={"X-Upload-Content-Type": content_type},
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    self.validate_response(status, contents, json, path, headers)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gcsfs/core.py", line 1222, in validate_response
    raise IOError("Forbidden: %s\n%s" % (path, msg))
OSError: Forbidden: https://www.googleapis.com/upload/storage/v1/b/merlin-datasets/o
Insufficient Permission
```

I should have both reading and writing permissions, as I can see in the IAM policy.
```
(rapids) root@b737df9c8ee2:/# gsutil iam get gs://merlin-datasets
{
  "bindings": [
    {
      "members": [
        "projectEditor:merlin-295819",
        "projectOwner:merlin-295819",
        "user:albertoa@nvidia.com"
      ],
      "role": "roles/storage.legacyBucketOwner"
    },
    {
      "members": [
        "projectViewer:merlin-295819"
      ],
      "role": "roles/storage.legacyBucketReader"
    },
    {
      "members": [
        "projectEditor:merlin-295819"
      ],
      "role": "roles/storage.legacyBucketWriter"
    },
    {
      "members": [
        "projectOwner:merlin-295819"
      ],
      "role": "roles/storage.legacyObjectOwner"
    },
    {
      "members": [
        "projectViewer:merlin-295819"
      ],
      "role": "roles/storage.legacyObjectReader"
    }
  ],
  "etag": "CAM="
}
```

I can actually upload a file to the bucket using `gsutil`
```
(rapids) root@b737df9c8ee2:/# gsutil cp test.py gs://merlin-datasets
Copying file://test.py [Content-Type=text/x-python]...
/ [1 files][  190.0 B/  190.0 B]                                                
Operation completed over 1 objects/190.0 B.   
```

**Comment by albert17** [comment]
It actually works from my machine. It does not work within the GCP Instance, I have to check permissions for the VM.

**Comment by martindurant** [comment]
You might want to try explicitly passing `token="cloud"` on the VM, if you want permissions to be picked up from the instance metadata - things may be getting confused about which is your "default" credentials. Also, it's useful to explicitly pass your project.
