### ISSUE TITLE
gcsfs version 0.7.2 causes aiohttp & fsspec errors when running pd.read_csv()/pd.read_parquet() from GCS

### ISSUE THREAD

**Issue by gndumbri** [dask/gcsfs#386]
**What happened**:

The following errors were thrown submitting a pyspark job to Dataproc. I have never run into this issue until today and my code is not different from the last time I successfully ran the same script (which was 4/21/21) on Dataproc as a pyspark job:

```
Job [6282a0c4e4be42ac87d678d43a2e520c] submitted.
Waiting for job output...
Exception ignored in: <function ClientSession.__del__ at 0x7f6880aef550>
Traceback (most recent call last):
  File "/opt/conda/default/lib/python3.8/site-packages/aiohttp/client.py", line 326, in __del__
    if not self.closed:
  File "/opt/conda/default/lib/python3.8/site-packages/aiohttp/client.py", line 963, in closed
    return self._connector is None or self._connector.closed
AttributeError: 'ClientSession' object has no attribute '_connector'
Traceback (most recent call last):
  File "/tmp/6282a0c4e4be42ac87d678d43a2e520c/rap5.py", line 221, in <module>
    hicnos, x = tfidf(path)
  File "/tmp/6282a0c4e4be42ac87d678d43a2e520c/rap5.py", line 21, in tfidf
    diags = pd.read_csv(path).dropna()
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/io/common.py", line 333, in _get_filepath_or_buffer
    file_obj = fsspec.open(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 428, in open
    return open_files(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 280, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/core.py", line 608, in get_fs_token_paths
    fs = cls(**options)
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/spec.py", line 69, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/gcsfs/core.py", line 269, in __init__
    self._session = sync(
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/opt/conda/default/lib/python3.8/site-packages/fsspec/implementations/http.py", line 25, in get_client
    return aiohttp.ClientSession(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'callback_timeout'
```

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

Note: below code run in Dataproc does not have "import gcsfs" since it is already integrated. Also no installations were done since all packages are preinstalled through conda on Dataproc.
```
import pandas as pd
df = pd.read_csv('gs://some-bucket/some_file.csv') # read a csv from GCS 
```

Note: below code run in a Google Colab Notebook was done with the latest versions of pyarrow and fsspec

```
!pip install gcsfs==0.7.2
!pip install pyarrow
!pip install fsspec

import gcsfs
import pandas as pd
df = pd.read_csv('gs://some-bucket/some_file.csv') # read a csv from GCS 

```

**Anything else we need to know?**:

I am wondering if this issue was triggered by the release of gcsfs 2021.4.0? The last time I used Dataproc was 4/20/21, and now I am getting these errors. Did the default version of gcsfs for the dataproc image 2.0-debian10 become 0.7.2 after the release of 2021.4.0? I have also raised an issue with aiohttp, but it seems to be that the gcsfs version 0.7.2 is the root cause. I have tested other versions of gcsfs in Google Colab (i.e. 0.7.1) and did not have this trouble. I also changed other packages' versions that are dependencies (for example, fsspec & aiohttp). Only when gcsfs was 0.7.2 did the errors get thrown.

**Environment**:

- Dask version: n/a
- Python version: 3.7 (Google Colab), 3.8.8 (Google Compute Engine VM through Google Dataproc cluster)
- Operating System: 2.0-debian10 for Compute Engine Instance, unknown for Google Colab Notebook
- Install method (conda, pip, source): !pip in Google Colab, no install performed on Compute Engine VM since everything is pre-installed and you can't overwrite the conda installation file (which I tried).
- aiohttp version 3.7.4 (Dataproc) 3.7.4.post0 (Google Colab)
- fsspec version 0.9.0 (Dataproc) 2021.4.0 (Google Colab)

**Comment by martindurant** [comment]
Sorry, I am confused by the version numbers you are reporting. 
gcsfs 2021.4.0 should be used with fsspec 2021.4.0. 
0.8.0 should be used with fsspec 0.9.0
0.7.x should be used with fsspec 0.8.0

(this is why versioning has changed to calendar-based).

The "exception ignored" part can indeed be ignored, it seems that aiohttp is trying to do cleanup during interpreter shutdown, when some attributes have themselves already been cleaned up.

**Comment by gndumbri** [comment]
Sorry for the confusion! The core issue is when running the code in Dataproc. When selecting the following Dataproc image type and version (image 2.0 with Debian 10), I get the error running the code I provided (the code I ran in Dataoproc). I then did SSH into the master node on the cluster (a Compute Engine VM instance) and checked the preinstalled version of gcsfs and it was 0.7.2. I attempted to update this but the files are read-only. Additionally, the other versions I provided were on this same instance. The fsspec version was 0.9.0.

I can't alter either of those versions (to my knowledge). Regardless if I could change the version, after testing in a Google Colab notebook, I was able to reproduce the error when I intentionally installed gcsfs version 0.7.2. The error does not occur with gcsfs 0.7.1, or 2021.4.0, but I can't set the version in Dataproc, so I submitted the issue.


<img width="1005" alt="Screen Shot 2021-04-30 at 1 17 51 PM" src="https://user-images.githubusercontent.com/3864120/116730429-7e1e7780-a9b6-11eb-8fee-bd6fd23a70d7.png">

**Comment by martindurant** [comment]
Right, so it's specifically gcsfs 0.7.2 that is incompatible with 0.9.0 of fsspec. You should be able to pip-install other versions by using the `--user` flag.

**Comment by gndumbri** [comment]
Thank you. I am not able to get this to work using the --user flag, but it's already been established that the versions are incompatible, so I'll need to resolve the issue with Dataproc as there isn't any further action needed here. Thanks!
